import '@/app/globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blog NextJS',
  description: 'Generated by create next app',
  manifest: '/manifest.json'
}

export default async function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={`${inter.className} bg-cover bg-center bg-white min-h-screen flex flex-col`} >
          <Header />
          {children}
      </body>
    </html>
  )
}
